Add scroll to grades table and move edit lesson to new tab
LQDJudge/online-judge pull request #131
Opened 2024-10-14 16:24 UTC by hanzomaster

2024-10-14 18:07 UTC, anhkha2003 reviewed
- Nên có thêm nút/tính năng cho add new lessons
- Nên xóa các đoạn comment code nếu sau này không dùng
- Nên xóa các đoạn code print debug
- Color hoặc background color không nên để trong file html, mà nên để trong file scss với tên class dễ phân biệt, tránh để global vì trùng tên với các file khác (ví dụ lesson-title hay edit-lesson-title thay vì title, và để trong file scss, ví dụ như course.scss)

2024-10-14 18:07 UTC, anhkha2003 commented on templates/course/edit_lesson.html
> +      color: blue !important;
Color/background color không nên để trong html, nên để vào file scss (ví dụ: course.scss). Nên để các biến trong class có tên dễ phân biệt, ví dụ edit-lesson-title

2024-10-14 18:07 UTC, anhkha2003 commented on templates/course/grades_lesson.html
> +    /*.static {
Nên xóa comment nếu đoạn này không dùng

2024-10-15 16:59 UTC, cuom1999 requested changes

2024-10-15 16:59 UTC, cuom1999 commented on judge/views/course.py
> +        problem_formsets = [
cái problem_formsets này không cần nữa. Mỗi cái formset đại diện cho các problem của lession. Vì trước có nhiều lesson trong 1 trang nên cần nhiều formset này. Giờ chỉ cần 1 là đủ. Hàm post sẽ hơi giống cái post của EditCourseContest.

2024-10-15 16:59 UTC, cuom1999 commented on judge/views/course.py
> +    def get_problem_formset(self, post=False, lesson=None):
hàm này không cần arg lesson nữa vì mình chỉ có 1 lesson. Trước cần nó vì mình có nhiều lesson trong 1 trang. Hàm này cũng giống hàm trong EditCourseContest.

2024-10-15 16:59 UTC, cuom1999 commented on templates/course/edit_lesson_new_window.html
> +{% extends "course/base.html" %}
Sau khi đổi backend thì cái này code giống course/edit_contest.html

2024-10-15 18:32 UTC, cuom1999 commented on judge/views/course.py
> +    def get(self, request, *args, **kwargs):
Với cái này nên sửa `def get` thành `def dispatch` để áp dụng cho cả post lẫn get. `dispatch` sẽ được chạy trước get, post nên trong cả get hay post request, mình sẽ có self.lesson (tham khảo EditCourseContest).

2024-10-20 17:01 UTC, hanzomaster commented
https://github.com/user-attachments/assets/9ce211c0-15df-4f23-a175-f5d94e292048

2024-10-22 05:50 UTC, merged