left-ui task
LQDJudge/online-judge pull request #75
Opened 2023-08-13 18:06 UTC by BaoLe106

2023-08-13 18:08 UTC, cuom1999 commented
Cho a xin ảnh UI (darkmode luôn)

2023-08-13 18:12 UTC, BaoLe106 commented
![b](https://github.com/LQDJudge/online-judge/assets/127121163/6ef30c6c-0083-4e26-9d81-b23b71b1832e)
![a](https://github.com/LQDJudge/online-judge/assets/127121163/06cd59fb-e527-4ab3-9cd7-f4742455b201)
dạ đây anh

2023-08-13 18:17 UTC, cuom1999 commented
Thanks em. Anh cũng không rõ cồng kềnh sao nhưng em có thể search GG "how to make a pull request github". Thường thì anh hay fork về (hoặc tạo một branch) xong dùng UI github tạo pull request.

2023-08-13 18:45 UTC, cuom1999 requested changes

2023-08-13 18:45 UTC, cuom1999 commented on resources/blog.scss
> +    margin-bottom: 10px;
2 dòng margin bottom với left này nhìn trên điện thoại không ok lắm. Với nếu được em thì dùng `em` thay vì px cho margin với padding cho giống mấy chỗ khác. Để test UI điện thoại thì mở inspect trong chrome rồi bấm nút toggle device (bên trái tab Element). Anh nghĩ UI điện thoại thì có thể để như hiện tại cũng được (không có border). Để chỉ áp dụng css cho desktop thì em thêm mấy css này vào bên trong block `@media (min-width: 800px)`. Tương tự `max-width: 799` là cho điện thoại.

2023-08-13 18:58 UTC, cuom1999 commented
với ý kiến cá nhân thì anh thấy để background cho từng item thành màu trắng + border màu #e3e3e3 thì nhìn sang hơn chút. 
![image](https://github.com/LQDJudge/online-judge/assets/47278241/ddca7d2a-e59b-430d-bfaf-8835ced0bdeb)

2023-08-13 19:04 UTC, cuom1999 commented
cái darkmode thì em có thể dùng DarkReader extension trên chrome để generate css rồi copy vào file darkmode.css (để generate css bằng DarkReader: Settings -> Manage Settings -> Export Dynamic Theme). Nếu cần thì nói a push một commit sau cũng được.

2023-08-17 13:52 UTC, BaoLe106 commented
anh ơi em mới commit lại 1 lần nữa anh xem qua coi thử có được chưa ạ

2023-08-17 14:22 UTC, merged