remake contest ui
LQDJudge/online-judge pull request #80
Opened 2023-09-07 08:29 UTC by HungBacktracking

<img width="960" alt="image" src="https://github.com/LQDJudge/online-judge/assets/89190591/1cf6de75-6d3e-4911-8200-174edf40052d">

2023-09-07 21:18 UTC, cuom1999 requested changes
chỉ một note nhỏ thôi

2023-09-07 21:18 UTC, cuom1999 commented on templates/contest/list.html
> +      box-shadow: 0px 4px 8px rgba(4, 83, 67, 0.2), 0px 6px 20px rgba(4, 83, 67, 0.19);
cái box-shadow này dính tới color nên em chuyển qua một file scss nào đó nhé.

2023-09-07 21:18 UTC, cuom1999 commented on templates/contest/list.html
> +      box-shadow: 0px 4px 8px rgba(4, 83, 67, 0.2), 0px 6px 20px rgba(4, 83, 67, 0.19);
để chuyển darkmode

2023-09-07 21:31 UTC, HungBacktracking commented on templates/contest/list.html
> +      box-shadow: 0px 4px 8px rgba(4, 83, 67, 0.2), 0px 6px 20px rgba(4, 83, 67, 0.19);
Dạ vậy giờ em chuyển mấy cái class có dính color đó sang 1 file scss phải không ạ

2023-09-07 21:37 UTC, cuom1999 commented on templates/contest/list.html
> +      box-shadow: 0px 4px 8px rgba(4, 83, 67, 0.2), 0px 6px 20px rgba(4, 83, 67, 0.19);
uh em, ví dụ contest.scss chẳng hạn. Chuyển xong thì compile lại là được. Khi chuyển qua đó thì tất cả các css tụ vào một file nên có thể ảnh hưởng cái list-contest nếu nó xuất hiện chỗ khác ngoài contest/list.html

2023-09-07 21:57 UTC, HungBacktracking commented on templates/contest/list.html
> +      box-shadow: 0px 4px 8px rgba(4, 83, 67, 0.2), 0px 6px 20px rgba(4, 83, 67, 0.19);
Dạ em đã xong ạ anh xem qua giúp em nha. Em cảm ơn anh.

2023-09-07 22:09 UTC, cuom1999 requested changes

2023-09-07 22:09 UTC, cuom1999 commented on templates/contest/list.html
> +              <div class="contest-title">Định dạng:</div>
Chỗ này nên thay "Định dạng" thành {{_("Format")}}, sau đó thêm bản dịch (có thể xem trong phần README.md)

2023-09-07 22:09 UTC, cuom1999 commented on templates/contest/list.html
> +              {% if contest.format_name == "default" %} IOI
chỗ này không cần if IOI, chỉ cần {{contest.format.name}}, cái này là property trả về class Format có name bên trong.

2023-09-07 22:09 UTC, cuom1999 commented on templates/contest/list.html
> +            <div class="contest-title">Người tham gia:</div>
tương tự cho "Người tham gia", mình nên dùng tiếng Anh rồi thêm bản dịch vào

2023-09-07 22:09 UTC, cuom1999 commented on templates/contest/list.html
> +            <div class="contest-title">Người tham gia:</div>
{{_("Users")}}

2023-09-07 22:12 UTC, cuom1999 commented
anh cảm giác cái khoảng cách này hơi nhỏ padding của tên kỳ thi (cột bên trái) hơi nhỏ hoặc font chữ nó hơi to làm nhìn hơi chật. Cái class kiểu [2022 78A] hay [rated], anh nghĩ nên cho xuống 1 dòng thay vì ngang dòng cái tên contest. 
![image](https://github.com/LQDJudge/online-judge/assets/47278241/a229d3aa-bccc-456a-b0ff-7ce448f8c1ae)

2023-09-07 22:15 UTC, HungBacktracking commented on templates/contest/list.html
> +              {% if contest.format_name == "default" %} IOI
dạ em if tại nếu format để mặc định thì nó hiện 'default' á anh

2023-09-07 22:18 UTC, cuom1999 commented on templates/contest/list.html
> +              {% if contest.format_name == "default" %} IOI
uh đúng là {{contest.format.name}} chứ không phải format_name, trước a nhầm. `format.name` sẽ giúp mình hiển thị cái tên của nó. Nếu e để qua tiếng Việt thì nó thành "Mặc định"

2023-09-07 22:18 UTC, HungBacktracking commented
Dạ tầm sáng em dậy em sửa nốt mọi thứ ạ

2023-09-07 22:38 UTC, cuom1999 commented
Optional: A thấy nếu không có cái nền trắng sẽ đẹp hơn. Cái này là do class wrapper trong `{{'wrapper' if is_two_column}}` ở file `three-column-content.html`. Cái `is_two_column` là từ `two-column-content.html` và `contest/list.html` extends cái `two-column-content.html`.

Để bỏ cái wrapper thì mình có thể làm thế này:
1. Trong contest/list.html, trước khi extends two-column-content.html thì mình `{% set no_wrapper = true %}`
2. Trong two-column-content.html, thay vì `{% set is_two_column = true %}` thì mình có thể làm kiểu {% set has_wrapper = not no_wrapper %} (để nếu None thì vẫn true).
3. Trong three-column-content.html, sửa `is_two_column` thành `has_wrapper`

2023-09-08 16:22 UTC, cuom1999 approved these changes
Thanks em!

2023-09-08 16:22 UTC, merged