Markdown Editor Task
LQDJudge/online-judge pull request #85
Opened 2023-09-27 12:35 UTC by BaoLe106

2023-09-27 19:43 UTC, cuom1999 requested changes

2023-09-27 19:43 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +    document.addEventListener("DOMContentLoaded", function() {
mấy cái này sau này em code jquery nhé.

2023-09-27 19:43 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +            <h2>Insert Image</h2>
mấy string tiếng Anh này em viết thành: `{{_('Insert Image')}}` để dịch sang tiếng Việt.
Để dịch sang tiếng Việt thì em làm các thao tác sau (copy từ readme)

Update vietnamese translation:
- python3 manage.py makemessages
- go to locale/vi
- modify .po file
- python3 manage.py compilemessages
- python3 manage.py compilejsi18n

2023-09-28 05:13 UTC, cuom1999 commented on judge/views/markdown_editor.py
> +                "title": ("Markdown Editor"),
Cái title này là dùng để cho cái <h2>, nếu em không thích thì bỏ đi cũng được. Còn nếu muốn giữ thì thêm `_("Markdown Editor")` để tạo bản dịch. Xong dịch tương tự như mấy cái bên frontend. Trước đó thì mình thêm dòng `from django.utils.translation import gettext_lazy as _`

2023-09-28 05:14 UTC, cuom1999 commented on judge/views/markdown_editor.py
> +from .preview import BlogMarkdownPreviewView
mấy cái không dùng thì nên xóa đi, không nên import

2023-09-28 05:16 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +  <div id="id_body-preview" data-preview-url="/widgets/preview/comment" data-textarea-id="wmd-input-id_body" data-timeout="1000" class="width-controller wmd-panel wmd-preview dmmd-preview dmmd-no-but
nên dùng `{{url('comment_preview')}}` thay vì `/widgets/preview/comment`

2023-09-28 05:17 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +    <form class="comment-submit-form" action="" method="post">
mình không submit gì thì bỏ `<form>` và cái dòng csrf dưới đi chắc cũng được (nếu không ảnh hưởng gì)

2023-09-28 05:18 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +      <input type="hidden" name="csrfmiddlewaretoken" value="Ngk7TfY2iIW4e9cPitl05k1c7xNUsVk9kCTkrAFveVmmcIhjRKv4GLtItKANAvae">
cái dòng này không cần thiết

2023-09-28 05:19 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +    document.addEventListener("DOMContentLoaded", function() {
mình có thể merge 2 cái <script> này vào một và đặt bên trong 
{% block js_media %}. Khi extends base.html thì JS đặt bên trong block js_media, còn css đặt bên trong block media

2023-09-28 05:21 UTC, cuom1999 commented on templates/markdown_editor/markdown_editor.html
> +      height: 678px;
không nên hardcode như thế này, mỗi màn hình có 1 độ cao khác nhau. Nên dùng kiểu calc(100vh - 30px) hoặc -webkit-fill-available cho height.

2023-09-29 16:26 UTC, BaoLe106 commented on judge/views/markdown_editor.py
> +                "title": ("Markdown Editor"),
Nhưng mà anh ơi em muốn bỏ trong web page chứ k bỏ trên title của tab á anh, có cách nào k anh chứ em bỏ là nó mất hết ở 2 chỗ

2023-09-29 17:08 UTC, BaoLe106 commented
Em fix lại rồi á anh. Anh xem lại thử còn gì chưa ổn nữa thì nói em.

2023-09-29 22:09 UTC, cuom1999 commented
Em fix lại thêm vài chỗ nhé:
- Bỏ dòng này (cái này là csrf token) <input type="hidden" name="csrfmiddlewaretoken" value="Ngk7TfY2iIW4e9cPitl05k1c7xNUsVk9kCTkrAFveVmmcIhjRKv4GLtItKANAvae">
- Dùng {{url('comment_preview')}} thay vì /widgets/preview/comment
- Đưa cái đống <script> trong file html vào {% block js_media %}
- Wrap mấy string tiếng Anh như "From the web", "From the internet", ... vào `{{_()}}` để dịch luôn.

2023-09-29 22:13 UTC, cuom1999 commented on judge/views/markdown_editor.py
> +                "title": ("Markdown Editor"),
Ah cái đó là {% block title_row %} trong base.html. Nó lấy biến title xong bỏ vào. Em có thể xóa nó đi bằng cách trong file html của em, override cái block đó thành rỗng:
```
{% block title_row %}{% endblock %}
```

2023-10-02 18:30 UTC, merged